apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecowordlylife
  labels:
    app: ecowordlylife
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecowordlylife
  template:
    metadata:
      labels:
        app: ecowordlylife
    spec:
      containers:
      - name: ecowordlylife-container
        image: 309395755719.dkr.ecr.us-east-1.amazonaws.com/ecowordlylife:latest
        ports:
        - containerPort: 3000
