apiVersion: v1
kind: Service
metadata:
  name: ecowordlylife
  labels:
    app: ecowordlylife
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ecowordlylife
  type: LoadBalancer
